name: Go Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CGO_ENABLED: 1

jobs:

  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install build-essential

      - name: Build
        run: go build -a -o build/anchor_linux_amd64 .
        env:
          GOOS: linux
          GOARCH: amd64
          CC: gcc

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: anchor_linux_amd64
          path: build/anchor_linux_amd64

  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross

      - name: Build
        run: go build -a -o build/anchor_linux_arm .
        env:
          GOOS: linux
          GOARCH: arm
          CC: arm-linux-gnueabihf-gcc

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: anchor_linux_arm
          path: build/anchor_linux_arm

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Build
        run: go build -a -o build/anchor_linux_arm64 .
        env:
          GOOS: linux
          GOARCH: arm64
          CC: aarch64-linux-gnu-gcc

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: anchor_linux_arm64
          path: build/anchor_linux_arm64

  build-windows-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install gcc-mingw-w64-x86-64

      - name: Build
        run: go build -a -o build/anchor_windows_amd64 .
        env:
          GOOS: windows
          GOARCH: amd64
          CC: gcc-mingw-w64-x86-64

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: anchor_windows_amd64
          path: build/anchor_windows_amd64
